---
# Source: example-chart/templates/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name:   release-name-example-chart
  labels:
    helm.sh/chart: example-chart-0.1.0
    app.kubernetes.io/name: example-chart
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
     
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: release-name-example-chart
      app.kubernetes.io/instance: release-name
  endpoints:
  - port: http
    path: '/actuator/prometheus'
    interval: 10s
    honorLabels: true
