apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-example-chart
  labels:
    helm.sh/chart: example-chart-0.1.0
    app.kubernetes.io/name: example-chart
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm